/** Reproduce the offline PDF reader assets from the pinned desktop dependency. */
import { cpSync, mkdirSync, copyFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { createRequire } from 'node:module'

const source = dirname(createRequire(import.meta.url).resolve('pdfjs-dist/package.json'))
const target = resolve(import.meta.dir, '../src/vendor/pdfjs')
const version = (await Bun.file(resolve(source, 'package.json')).json()).version
if (version !== '6.3.289') throw Error(`Unexpected PDF.js version: ${version}`)
mkdirSync(target, { recursive: true })
copyFileSync(resolve(source, 'build/pdf.min.mjs'), resolve(target, 'pdf.mjs'))
copyFileSync(resolve(source, 'build/pdf.worker.min.mjs'), resolve(target, 'pdf.worker.mjs'))
copyFileSync(resolve(source, 'LICENSE'), resolve(target, 'LICENSE'))
for (const directory of ['cmaps', 'standard_fonts']) cpSync(resolve(source, directory), resolve(target, directory), { recursive: true })
await Bun.write(resolve(target, 'README.md'), `PDF.js ${version}, Mozilla, Apache-2.0.\n\nGenerated by \`bun run vendor:pdf\` in apps/desktop. The reader uses only these bundled assets; no CDN.\n`)
