import {afterEach,beforeEach,describe,expect,it} from 'vitest'
import {execFileSync} from 'node:child_process'
import {randomUUID,createHash} from 'node:crypto'
import {chmodSync,cpSync,existsSync,linkSync,lstatSync,mkdirSync,mkdtempSync,readFileSync,readdirSync,realpathSync,renameSync,rmSync,symlinkSync,unlinkSync,writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {openDb,type Db} from '../../lib/db'
import {createRestoreManager,type RestoreReview} from './restore-manager'
import {RESTORE_SCHEMA_SQL} from './restore-store'

let root:string,project:string,blobs:string,db:Db,writer=false
const identity=(path:string)=>{const s=lstatSync(path,{bigint:true});return `${s.dev}:${s.ino}`}
const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex')
function git(...args:string[]){return execFileSync('git',args,{cwd:project,encoding:'utf8',env:{...process.env,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1'}})}
async function readGitState(){const index:Record<string,string>={};for(const row of git('ls-files','--stage','-z').split('\0').filter(Boolean)){const [meta,path]=row.split('\t');index[path!]=(index[path!]??'')+meta+'\n'}return {head:git('rev-parse','HEAD').trim(),index}}
const make=()=>createRestoreManager({db,blobRoot:blobs,readGitState,withMutation:async <T>(_id:string,op:()=>Promise<T>)=>op(),assertWriterClosed:()=>{if(writer)throw Error('writer_open')}})
let manager:ReturnType<typeof make>
beforeEach(()=>{root=realpathSync(mkdtempSync(join(tmpdir(),'cc-restore-')));project=join(root,'work');blobs=join(root,'private');mkdirSync(project);git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');writeFileSync(join(project,'file.txt'),'before\r\n');git('add','.');git('commit','-qm','base');db=openDb({path:join(root,'state.sqlite')});db.exec(RESTORE_SCHEMA_SQL);writer=false;manager=make()})
afterEach(()=>{db.close();rmSync(root,{recursive:true,force:true})})
const begin=()=>manager.begin({workspaceId:'workspace',taskId:'task',runId:randomUUID(),path:project,directoryIdentity:identity(project)})
async function closed(change:()=>void){const run=await begin();change();manager.markClosing(run.restoreRunId);const review=await manager.close(run.restoreRunId);manager.bindArtifact(run.restoreRunId,'artifact','a'.repeat(64));return manager.list('workspace').find(r=>r.restoreRunId===review.restoreRunId)!}
function request(review:RestoreReview,path='file.txt'){return {workspaceId:'workspace',taskId:'task',artifactId:review.artifactId!,path,changeId:review.files.find(f=>f.path===path)!.changeId,requestId:randomUUID()}}

describe('private restore lifecycle and exact file effects',()=>{
  it('keeps before through retained activity and only exposes a restore after confirmed close',async()=>{const run=await begin();writeFileSync(join(project,'file.txt'),'round one');expect(manager.list('workspace')[0]!.files).toEqual([]);writer=true;manager.markClosing(run.restoreRunId);await expect(manager.close(run.restoreRunId)).rejects.toThrow('writer_open');manager.markUncertain(run.restoreRunId);expect(manager.blocked('workspace')).toBe(true);writer=false;writeFileSync(join(project,'file.txt'),'round two');await manager.close(run.restoreRunId);manager.bindArtifact(run.restoreRunId,'artifact','a'.repeat(64));const result=await manager.revert(request(manager.list('workspace')[0]!));expect(result.state).toBe('reverted');expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('before\r\n')})
  it('restores exact BOM/CRLF bytes and mode, deletes proven additions, restores empty deletion',async()=>{const original=Buffer.from('\ufeffbefore\r\n');writeFileSync(join(project,'file.txt'),original);chmodSync(join(project,'file.txt'),0o755);writeFileSync(join(project,'empty.txt'),'');git('add','.');git('commit','-qm','bytes');const review=await closed(()=>{writeFileSync(join(project,'file.txt'),'changed\n');chmodSync(join(project,'file.txt'),0o644);writeFileSync(join(project,'new.txt'),'new');unlinkSync(join(project,'empty.txt'))});for(const path of ['file.txt','new.txt','empty.txt'])expect((await manager.revert(request(review,path))).state).toBe('reverted');expect(readFileSync(join(project,'file.txt'))).toEqual(original);if(process.platform!=='win32')expect(lstatSync(join(project,'file.txt')).mode&0o777).toBe(0o755);expect(existsSync(join(project,'new.txt'))).toBe(false);expect(readFileSync(join(project,'empty.txt')).length).toBe(0)})
  it('never treats an ignored preexisting file as an absent before',async()=>{writeFileSync(join(project,'.gitignore'),'hidden.txt\n');writeFileSync(join(project,'hidden.txt'),'private before');git('add','.gitignore');git('commit','-qm','ignore');const review=await closed(()=>{writeFileSync(join(project,'.gitignore'),'');writeFileSync(join(project,'hidden.txt'),'visible after')});expect(review.files.find(f=>f.path==='hidden.txt')).toMatchObject({state:'blocked'});await expect(manager.revert(request(review,'hidden.txt'))).rejects.toThrow();expect(readFileSync(join(project,'hidden.txt'),'utf8')).toBe('visible after')})
  it.each(['non_utf8','large','symlink','hardlink'])('blocks unsupported %s before/after',async kind=>{const review=await closed(()=>{if(kind==='non_utf8')writeFileSync(join(project,'file.txt'),Buffer.from([255]));if(kind==='large')writeFileSync(join(project,'file.txt'),Buffer.alloc(256*1024+1,65));if(kind==='symlink'){unlinkSync(join(project,'file.txt'));symlinkSync('other.txt',join(project,'file.txt'))}if(kind==='hardlink')linkSync(join(project,'file.txt'),join(project,'alias.txt'))});expect(review.files.find(f=>f.path==='file.txt')?.state).toBe('blocked')})
  it.each(['head','index','staged_before','later_content','directory','generation','task','artifact','change'])('rejects stale or misbound %s with zero file effects',async kind=>{if(kind==='directory'){mkdirSync(join(project,'dir'));renameSync(join(project,'file.txt'),join(project,'dir/file.txt'));git('add','.');git('commit','-qm','dir')};const path=kind==='directory'?'dir/file.txt':'file.txt';if(kind==='staged_before'){writeFileSync(join(project,path),'staged');git('add','.')};const review=await closed(()=>writeFileSync(join(project,path),'after'));if(kind==='head')git('commit','--allow-empty','-qm','next');if(kind==='index')git('add','.');if(kind==='later_content')writeFileSync(join(project,path),'external');if(kind==='directory'){renameSync(join(project,'dir'),join(project,'old'));mkdirSync(join(project,'dir'));writeFileSync(join(project,path),'after')};if(kind==='generation'){const run=await begin();await manager.close(run.restoreRunId)};const input=request(review,path);if(kind==='task')input.taskId='another';if(kind==='artifact')input.artifactId='another';if(kind==='change')input.changeId='another';const before=hash(readFileSync(join(project,path)));await expect(manager.revert(input)).rejects.toThrow();expect(hash(readFileSync(join(project,path)))).toBe(before)})
  it('replays the same receipt without effects and rejects request ID reuse',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));const input=request(review),first=await manager.revert(input);writeFileSync(join(project,'file.txt'),'later');expect(await manager.revert(input)).toEqual(first);await expect(manager.revert({...input,path:'other.txt'})).rejects.toThrow('request_conflict');expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('later')})
  it('rejects damaged raw blobs without writing a file',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));for(const name of readdirSync(blobs))if(/^[a-f0-9]{64}$/.test(name))writeFileSync(join(blobs,name),'corrupt');await expect(manager.revert(request(review))).rejects.toThrow('blob');expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('after')})
  it('journals before effect, blocks after a receipt failure, and recovers across SQLite reopen',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));const input=request(review);db.exec("CREATE TRIGGER fail_receipt BEFORE UPDATE ON workbench_restore_operations WHEN NEW.state='reverted' BEGIN SELECT RAISE(ABORT,'receipt_failed'); END");await expect(manager.revert(input)).rejects.toThrow();expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('before\r\n');expect(manager.blocked('workspace')).toBe(true);await expect(begin()).rejects.toThrow();db.exec('DROP TRIGGER fail_receipt');db.close();db=openDb({path:join(root,'state.sqlite')});manager=make();await manager.recover('workspace');expect((await manager.revert(input)).state).toBe('reverted');expect(manager.blocked('workspace')).toBe(false)})
  it('manual keep-current requires a fresh observation and changes no bytes',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));const input=request(review);db.exec("CREATE TRIGGER fail_receipt BEFORE UPDATE ON workbench_restore_operations WHEN NEW.state='reverted' BEGIN SELECT RAISE(ABORT,'receipt_failed'); END");await expect(manager.revert(input)).rejects.toThrow();db.exec('DROP TRIGGER fail_receipt');writeFileSync(join(project,'file.txt'),'external');await manager.recover('workspace');const file=manager.list('workspace')[0]!.files[0]!;expect(file.state).toBe('needs_recovery');const resolve={workspaceId:'workspace',taskId:'task',operationId:file.operationId!,observedFingerprint:file.observedFingerprint!};writeFileSync(join(project,'file.txt'),'newer external');await expect(manager.resolveKeepCurrent(resolve)).rejects.toThrow('observation_changed');await manager.recover('workspace');const fresh=manager.list('workspace')[0]!.files[0]!;expect((await manager.resolveKeepCurrent({...resolve,observedFingerprint:fresh.observedFingerprint!})).state).toBe('resolved_keep_current');expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('newer external');expect(manager.blocked('workspace')).toBe(false)})
  it('rejects a case-alias replacement even when bytes and inode still match',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));renameSync(join(project,'file.txt'),join(project,'FILE.txt'));await expect(manager.revert(request(review))).rejects.toThrow();expect(readFileSync(join(project,'FILE.txt'),'utf8')).toBe('after')})
  it('resumes a known applying temporary file after interruption before rename',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));let interrupted=false;const proxied=new Proxy(db,{get(target,key){if(key==='query')return (sql:string)=>{const statement=target.query(sql);if(!sql.startsWith('UPDATE workbench_restore_operations'))return statement;return new Proxy(statement,{get(stmt,method){if(method==='run')return (...args:unknown[])=>{const result=stmt.run(...args as never[]);if(args[0]==='applying'&&!interrupted){interrupted=true;throw Error('interrupted_before_rename')}return result};const value=Reflect.get(stmt,method);return typeof value==='function'?value.bind(stmt):value}})};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value}}) as Db;manager=createRestoreManager({db:proxied,blobRoot:blobs,readGitState,withMutation:async(_id,op)=>op(),assertWriterClosed:()=>{}});const input=request(review);await expect(manager.revert(input)).rejects.toThrow('interrupted_before_rename');expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('after');manager=make();await manager.recover('workspace');expect((await manager.revert(input)).state).toBe('reverted');expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('before\r\n');expect(readdirSync(project).some(n=>n.startsWith('.cc-workbench-restore-'))).toBe(false)})
  it('persists prepared before a disk write failure and retries safely when the disk is writable',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));const input=request(review);chmodSync(project,0o500);try{await expect(manager.revert(input)).rejects.toThrow();expect(manager.blocked('workspace')).toBe(true);expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('after')}finally{chmodSync(project,0o700)}await manager.recover('workspace');expect((await manager.revert(input)).state).toBe('reverted')})
  it('keeps a root-replaced workspace blocked after manual keep-current',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));db.exec("CREATE TRIGGER fail_receipt BEFORE UPDATE ON workbench_restore_operations WHEN NEW.state='reverted' BEGIN SELECT RAISE(ABORT,'receipt_failed'); END");await expect(manager.revert(request(review))).rejects.toThrow();db.exec('DROP TRIGGER fail_receipt');renameSync(project,join(root,'old-work'));mkdirSync(project);writeFileSync(join(project,'file.txt'),'replacement');await manager.recover('workspace');const file=manager.list('workspace')[0]!.files[0]!;expect((await manager.resolveKeepCurrent({workspaceId:'workspace',taskId:'task',operationId:file.operationId!,observedFingerprint:file.observedFingerprint!})).state).toBe('resolved_keep_current');expect(manager.blocked('workspace')).toBe(true);await expect(begin()).rejects.toThrow();expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('replacement')})
  it('does not replay after a writer or Git state changes during restart recovery',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));db.exec("CREATE TRIGGER fail_receipt BEFORE UPDATE ON workbench_restore_operations WHEN NEW.state='reverted' BEGIN SELECT RAISE(ABORT,'receipt_failed'); END");const input=request(review);await expect(manager.revert(input)).rejects.toThrow();db.exec('DROP TRIGGER fail_receipt');writer=true;await manager.recover('workspace');expect((await manager.revert(input)).state).toBe('needs_recovery');writer=false;git('commit','--allow-empty','-qm','changed');await manager.recover('workspace');expect(manager.list('workspace')[0]!.files[0]!.reason).toBe('git_state_changed');expect(manager.blocked('workspace')).toBe(true)})
  it('blocks files beyond total raw-byte coverage without truncating captured versions',async()=>{for(let i=0;i<65;i++)writeFileSync(join(project,`budget-${String(i).padStart(2,'0')}.txt`),Buffer.alloc(256*1024,65));const review=await closed(()=>writeFileSync(join(project,'budget-64.txt'),'changed'));expect(review.files.find(f=>f.path==='budget-64.txt')?.state).toBe('blocked');await expect(manager.revert(request(review,'budget-64.txt'))).rejects.toThrow();expect(readFileSync(join(project,'budget-64.txt'),'utf8')).toBe('changed')})
  it('never infers absence beyond the actual existence coverage limit',async()=>{mkdirSync(join(project,'ignored'));writeFileSync(join(project,'.gitignore'),'ignored/*\n');for(let i=0;i<50_001;i++)writeFileSync(join(project,'ignored',String(i)),'');const review=await closed(()=>{writeFileSync(join(project,'.gitignore'),'ignored/*\n!ignored/!new.txt\n');writeFileSync(join(project,'ignored/!new.txt'),'new')});expect(review.files.find(f=>f.path==='ignored/!new.txt')?.state).toBe('blocked');await expect(manager.revert(request(review,'ignored/!new.txt'))).rejects.toThrow();expect(readFileSync(join(project,'ignored/!new.txt'),'utf8')).toBe('new')})
  it('public DTOs never expose blobs, private storage paths, or directory identities',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));const output=JSON.stringify({review,operation:await manager.revert(request(review))});expect(output).not.toContain(blobs);expect(output).not.toContain('blobSha');expect(output).not.toContain('directoryIdentity');expect(output).not.toContain('temporaryPath')})

  it('the public closed-session diff preserves CRLF text lines',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'round two\r\n'));expect(review.review.files[0]!.diff).toContain('-before\r\n');expect(review.review.files[0]!.diff).toContain('+round two\r\n')})
  it('restores ordinary files named like object prototype members',async()=>{writeFileSync(join(project,'__proto__'),'original');const review=await closed(()=>writeFileSync(join(project,'__proto__'),'after'));expect((await manager.revert(request(review,'__proto__'))).state).toBe('reverted');expect(readFileSync(join(project,'__proto__'),'utf8')).toBe('original')})
  it('a prepared journal survives total receipt-write failure and blocks a new writer',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));const input=request(review);db.exec("CREATE TRIGGER all_updates_fail BEFORE UPDATE ON workbench_restore_operations BEGIN SELECT RAISE(ABORT,'disk_full'); END");await expect(manager.revert(input)).rejects.toThrow();expect((await manager.revert(input)).state).toBe('prepared');expect(manager.blocked('workspace')).toBe(true);await expect(begin()).rejects.toThrow('workspace_blocked');expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('after');db.exec('DROP TRIGGER all_updates_fail');await manager.recover('workspace');expect((await manager.revert(input)).state).toBe('reverted')})
  it('operates on a linked worktree without changing the source, either index, or refs',async()=>{const source=project,sourceBytes=readFileSync(join(source,'file.txt')),sourceHead=git('rev-parse','HEAD');git('worktree','add','-qb','isolated',join(root,'isolated'));const sourceIndex=readFileSync(join(source,'.git/index'));project=join(root,'isolated');const executionIndex=git('rev-parse','--git-path','index').trim();const indexBefore=readFileSync(executionIndex),refsBefore=git('show-ref');const review=await closed(()=>writeFileSync(join(project,'file.txt'),'changed'));await manager.revert(request(review));expect(readFileSync(join(source,'file.txt'))).toEqual(sourceBytes);expect(readFileSync(join(source,'.git/index'))).toEqual(sourceIndex);expect(readFileSync(executionIndex)).toEqual(indexBefore);expect(git('show-ref')).toBe(refsBefore);expect(execFileSync('git',['rev-parse','HEAD'],{cwd:source,encoding:'utf8'})).toBe(sourceHead)})
  it('freezes artifact binding and rejects missing parent or unsafe request paths',async()=>{mkdirSync(join(project,'dir'));writeFileSync(join(project,'dir/child.txt'),'before');git('add','.');git('commit','-qm','nested');const review=await closed(()=>rmSync(join(project,'dir'),{recursive:true}));expect(()=>manager.bindArtifact(review.restoreRunId,'other','b'.repeat(64))).toThrow('artifact_conflict');await expect(manager.revert(request(review,'dir/child.txt'))).rejects.toThrow();for(const path of ['../file.txt','/file.txt','dir\\file.txt','file.txt:ads','NUL','file.txt.'])await expect(manager.revert({...request(review,'dir/child.txt'),path})).rejects.toThrow('invalid_restore_request');expect(existsSync(join(project,'dir'))).toBe(false)})

  it('commits task events with the receipt and path version, rolling all three back on callback failure',async()=>{const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'));db.exec('CREATE TABLE fixture_events(operation_id TEXT PRIMARY KEY)');let fail=true;manager=createRestoreManager({db,blobRoot:blobs,readGitState,withMutation:async(_id,op)=>op(),assertWriterClosed:()=>{},onOperationCommitted:operation=>{db.query('INSERT INTO fixture_events(operation_id) VALUES(?)').run(operation.operationId);if(fail)throw Error('event_commit_failed')}});const input=request(review);await expect(manager.revert(input)).rejects.toThrow('event_commit_failed');expect(db.query<{count:number},[]>('SELECT COUNT(*) AS count FROM fixture_events').get()!.count).toBe(0);expect(db.query<{version:string},[]>('SELECT change_id AS version FROM workbench_restore_paths').get()!.version).toBe(input.changeId);expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('before\r\n');fail=false;await manager.recover('workspace');expect((await manager.revert(input)).state).toBe('reverted');expect(db.query<{count:number},[]>('SELECT COUNT(*) AS count FROM fixture_events').get()!.count).toBe(1);await manager.recover('workspace');expect(db.query<{count:number},[]>('SELECT COUNT(*) AS count FROM fixture_events').get()!.count).toBe(1)})

  it('refuses to start when the root is replaced while capturing the initial Git state',async()=>{let once=false;manager=createRestoreManager({db,blobRoot:blobs,readGitState:async()=>{const state=await readGitState();if(!once){once=true;renameSync(project,join(root,'old-work'));cpSync(join(root,'old-work'),project,{recursive:true})}return state},withMutation:async(_id,op)=>op(),assertWriterClosed:()=>{}});await expect(begin()).rejects.toThrow('directory_identity_changed');expect(manager.blocked('workspace')).toBe(true);expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('before\r\n')})

  it('rejects an in-workspace blob root whose component begins with two dots',async()=>{blobs=join(project,'..secret');manager=make();await expect(begin()).rejects.toThrow('unsafe_blob_root');expect(existsSync(blobs)).toBe(false)})
  it.each(['directory','symlink','ancestor_symlink'])('refuses a replaced private blob root (%s) before any new snapshot writes',async kind=>{
    if(kind==='ancestor_symlink'){blobs=join(root,'container','private');manager=make()}
    const review=await closed(()=>writeFileSync(join(project,'file.txt'),'after'))
    if(kind==='ancestor_symlink'){renameSync(join(root,'container'),join(root,'saved-container'));symlinkSync(join(root,'saved-container'),join(root,'container'))}
    else{const saved=join(root,'saved-private');renameSync(blobs,saved);if(kind==='directory')mkdirSync(blobs);else symlinkSync(saved,blobs)}
    const before=hash(readFileSync(join(project,'file.txt')));manager=make()
    await expect(manager.revert(request(review))).rejects.toThrow('blob')
    await expect(begin()).rejects.toThrow('blob')
    expect(hash(readFileSync(join(project,'file.txt')))).toBe(before)
    if(kind==='directory')expect(readdirSync(blobs)).toEqual([])
  })

  it('uses execution-relative Git paths when the task is a repository subdirectory',async()=>{const repository=project;mkdirSync(join(project,'sub'));writeFileSync(join(project,'sub/file.txt'),'child before');git('add','.');git('commit','-qm','child');project=join(project,'sub');const review=await closed(()=>writeFileSync(join(project,'file.txt'),'child after'));expect(review.files.map(f=>f.path)).toEqual(['file.txt']);expect((await manager.revert(request(review))).state).toBe('reverted');expect(readFileSync(join(project,'file.txt'),'utf8')).toBe('child before');expect(readFileSync(join(repository,'file.txt'),'utf8')).toBe('before\r\n')})

})
