// Helper: build a minimal DoctorReport that produces a given diagnosis code.
// These shapes must match what diagnose() in view.js expects.
export const REPORTS = {
  // code-1: daemon dead + pid≠null + service installed → "后台服务挂了"
  deadDaemon: {
    ready: true,
    stateDir: '/tmp/wechat-cc-shim',
    runtime: 'source',
    wslDetected: false,
    checks: {
      bun:      { ok: true, path: '/usr/local/bin/bun' },
      git:      { ok: true, path: '/usr/bin/git' },
      claude:   { ok: true, path: '/usr/local/bin/claude' },
      codex:    { ok: true, path: '/usr/local/bin/codex' },
      cursor:   { ok: false, apiKeySet: false, sdkInstalled: true },
      accounts: { ok: true, count: 1, items: [{ id: 'bot1-im-bot', botId: 'bot1', userId: 'u1', baseUrl: '' }] },
      access:   { ok: true, dmPolicy: 'allowlist', allowFromCount: 1 },
      provider: { ok: true, provider: 'claude', binaryPath: '/usr/local/bin/claude' },
      daemon:   { alive: false, pid: 9999 },
      service:  { installed: true, kind: 'launchagent' },
    },
    userNames: { u1: 'Test User' },
    expiredBots: [],
    nextActions: [],
  },
  // code-5 (expired): daemon alive + expiredBots non-empty → "微信账号已过期"
  accountExpired: {
    ready: true,
    stateDir: '/tmp/wechat-cc-shim',
    runtime: 'source',
    wslDetected: false,
    checks: {
      bun:      { ok: true, path: '/usr/local/bin/bun' },
      git:      { ok: true, path: '/usr/bin/git' },
      claude:   { ok: true, path: '/usr/local/bin/claude' },
      codex:    { ok: true, path: '/usr/local/bin/codex' },
      cursor:   { ok: false, apiKeySet: false, sdkInstalled: true },
      accounts: { ok: true, count: 1, items: [{ id: 'bot1-im-bot', botId: 'bot1', userId: 'u1', baseUrl: '' }] },
      access:   { ok: true, dmPolicy: 'allowlist', allowFromCount: 1 },
      provider: { ok: true, provider: 'claude', binaryPath: '/usr/local/bin/claude' },
      daemon:   { alive: true, pid: 12345 },
      service:  { installed: true, kind: 'launchagent' },
    },
    userNames: { u1: 'Test User' },
    expiredBots: [{ botId: 'bot1', firstSeenExpiredAt: Date.now() - 3600000 }],
    nextActions: [],
  },
  // code-4: daemon alive + claude.severity='hard' → "AI 工具缺失"
  providerMissing: {
    ready: true,
    stateDir: '/tmp/wechat-cc-shim',
    runtime: 'source',
    wslDetected: false,
    checks: {
      bun:      { ok: true, path: '/usr/local/bin/bun' },
      git:      { ok: true, path: '/usr/bin/git' },
      claude:   { severity: 'hard', fix: { command: 'npm install -g @anthropic-ai/claude-code' } },
      codex:    { ok: true, path: '/usr/local/bin/codex' },
      cursor:   { ok: false, apiKeySet: false, sdkInstalled: true },
      accounts: { ok: true, count: 1, items: [{ id: 'bot1-im-bot', botId: 'bot1', userId: 'u1', baseUrl: '' }] },
      access:   { ok: true, dmPolicy: 'allowlist', allowFromCount: 1 },
      provider: { ok: false, provider: 'claude' },
      daemon:   { alive: true, pid: 12345 },
      service:  { installed: true, kind: 'launchagent' },
    },
    userNames: { u1: 'Test User' },
    expiredBots: [],
    nextActions: [],
  },
  // code-0: all green → brief "连接正常" feedback
  allGreen: {
    ready: true,
    stateDir: '/tmp/wechat-cc-shim',
    runtime: 'source',
    wslDetected: false,
    checks: {
      bun:      { ok: true, path: '/usr/local/bin/bun' },
      git:      { ok: true, path: '/usr/bin/git' },
      claude:   { ok: true, path: '/usr/local/bin/claude' },
      codex:    { ok: true, path: '/usr/local/bin/codex' },
      cursor:   { ok: false, apiKeySet: false, sdkInstalled: true },
      accounts: { ok: true, count: 1, items: [{ id: 'bot1-im-bot', botId: 'bot1', userId: 'u1', baseUrl: '' }] },
      access:   { ok: true, dmPolicy: 'allowlist', allowFromCount: 1 },
      provider: { ok: true, provider: 'claude', binaryPath: '/usr/local/bin/claude' },
      daemon:   { alive: true, pid: 12345 },
      service:  { installed: true, kind: 'launchagent' },
    },
    userNames: { u1: 'Test User' },
    expiredBots: [],
    nextActions: [],
  },
}
